[package]
name = "hazelcast-rs-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
syn = { version = "1.0.105", features = ["full"] }
syn_derive = "0.1.2"
quote = "1.0.21"
convert_case = "0.6.0"
